# Generated by Django 2.0 on 2022-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='public_key',
            field=models.TextField(blank=True),
        ),
    ]
