# Generated by Django 2.0 on 2022-04-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220407_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='public_key',
        ),
    ]
