# Generated by Django 2.1.7 on 2022-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
